# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Servergo < Formula
  desc "快速的HTTP文件服务器工具，类似于Python的http.server模块，但提供更好的性能和更多功能"
  homepage "https://github.com/CC11001100/servergo"
  version "0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CC11001100/servergo/releases/download/v0.1/servergo_0.1_darwin_amd64.tar.gz"
      sha256 "9c047218adac33c0ffae050b2dca2e11e6f01724fb9a2641830167658d3e48e8"

      def install
        bin.install "servergo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CC11001100/servergo/releases/download/v0.1/servergo_0.1_darwin_arm64.tar.gz"
      sha256 "d34cd9ad8de55fe142658dbf371b312155896385bb10c5b53d356ae91916fe98"

      def install
        bin.install "servergo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/CC11001100/servergo/releases/download/v0.1/servergo_0.1_linux_amd64.tar.gz"
      sha256 "5e97b8e65f1fd800b002638bded8b87963ce711f3314c091e2bd2122228c9b02"
      def install
        bin.install "servergo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/CC11001100/servergo/releases/download/v0.1/servergo_0.1_linux_arm64.tar.gz"
      sha256 "1ea5d746cef0b35780e698d85107ed917b42063ae63412c15e5af13c0b340b4f"
      def install
        bin.install "servergo"
      end
    end
  end

  test do
    system "#{bin}/servergo version"
  end
end
